import React from 'react'; 
import ReactDOM from 'react-dom/client'; 
import './index.css'; 
import App from './App'; 
import AgencyPortal from './AgencyApp'; 
import { BrowserRouter, Routes, Route } from 'react-router-dom'; 
import reportWebVitals from './reportWebVitals'; 
const root = ReactDOM.createRoot(document.getElementById('root')); 
root.render(<React.StrictMode><BrowserRouter><Routes><Route path="/" element={<App />} /><Route path="/agency" element={<AgencyPortal />} /></Routes></BrowserRouter></React.StrictMode>); 
reportWebVitals(); 
